name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.72.0  # MSRV

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy, hack

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --feature-powerset

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --feature-powerset -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --feature-powerset -- -D warnings
